-- AlterEnum: Adiciona novos tipos de notificação
-- Gap #2 (PAYMENT_REJECTED), Gap #4 (ORDER_AUTO_COMPLETED), Gap #5 (DISPUTE_WINDOW_CLOSING)
-- + ORDER_DELIVERED como utilitário

ALTER TABLE `notifications` MODIFY COLUMN `type` ENUM(
  'WELCOME',
  'PAYMENT_CONFIRMED',
  'PAYMENT_REJECTED',
  'ORDER_SHIPPED',
  'ITEM_SOLD',
  'ORDER_DELIVERED',
  'ORDER_AUTO_COMPLETED',
  'DISPUTE_WINDOW_CLOSING',
  'PASSWORD_RESET',
  'DISPUTE_OPENED',
  'DISPUTE_RESPONDED',
  'DISPUTE_RESOLVED',
  'SUBSCRIPTION_PAYMENT_FAILED',
  'SUBSCRIPTION_EXPIRED'
) NOT NULL;

ALTER TABLE `notification_preferences` MODIFY COLUMN `type` ENUM(
  'WELCOME',
  'PAYMENT_CONFIRMED',
  'PAYMENT_REJECTED',
  'ORDER_SHIPPED',
  'ITEM_SOLD',
  'ORDER_DELIVERED',
  'ORDER_AUTO_COMPLETED',
  'DISPUTE_WINDOW_CLOSING',
  'PASSWORD_RESET',
  'DISPUTE_OPENED',
  'DISPUTE_RESPONDED',
  'DISPUTE_RESOLVED',
  'SUBSCRIPTION_PAYMENT_FAILED',
  'SUBSCRIPTION_EXPIRED'
) NOT NULL;
