name: Bug
description: Correção de erro
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    id: descricao
    attributes:
      label: Descrição do problema
    validations:
      required: true

  - type: textarea
    id: esperado
    attributes:
      label: Comportamento esperado
    validations:
      required: true
